- .eslintignore
- .eslintrc
- .prettierrc
- .remarkrc
- .storybook/main.js
- .stylelintrc
- package.json
- src/accordion/accordion.component.ts
- src/autocomplete/autocomplete-placeholder.component.ts
- src/notification/notification.service.spec.ts
- src/select/option-placeholder.component.ts
- src/tooltip/tooltip-copy.directive.ts
- src/tree-select/tree-node-placeholder.component.ts
- stories/checkbox/checkbox.stories.mdx
- stories/radio/radio.stories.mdx
- stories/switch/switch.stories.mdx
- stories/table-of-contents/toc.stories.mdx
- stories/tooltip/tooltip.stories.mdx
- tsconfig.json
- yarn.lock
remove unnecessary dependencies
> feat!: upgrade to Angular 10

- src/input/input.component.scss
- src/input/tags-input/tags-input.component.html
tags-input如果采用ngModel形式，会在control设置具体value前，预先发一个null值，导致(value$ | async).length出错
> fix: input min-width error and tags input value may null

- src/dialog/confirm-dialog/confirm-dialog-config.ts
- src/dialog/confirm-dialog/confirm-dialog.component.ts
- src/dialog/dialog.service.spec.ts
- src/dialog/dialog.types.ts
> feat: support return Promise/Observable directly for ConfirmDialog

- src/nav-menu/nav-item-group/nav-item-group.component.ts
- src/nav-menu/platform-nav/__snapshots__/platform-nav.component.spec.ts.snap
fix aui-platform-nav 通过groups传入左导航数据时 title 不显示的bug
> fix: aui-platform-nav title not display fix

- .changeset/shiny-chicken-behave.md
- .changeset/thick-windows-smell.md
- src/form/__snapshots__/form.component.spec.ts.snap
- src/form/form-item/form-item.component.ts
这里思考过后还是不应该在aui里去决定使用场景的默认item width，可能也会对现有项目特殊组件产生影响，所以决定去掉默认值。
对于项目中大部分表单元素都是medium的长度的情况，我觉得可以在项目的通用样式中添加全局的初始值就可以了
> fix: remove form item width

- .changeset/ninety-pens-wink.md
- src/tree-select/tree-select.component.ts
> fix: tree-select `labelFn` takes higher priority than `label`

- .changeset/fuzzy-scissors-hunt.md
- src/table/table-scroll.directive.ts
- src/table/table-scroll.scss
- src/table/table.component.scss
- src/table/table.module.ts
- stories/table/sticky-columns/sticky-columns-demo.component.html
- stories/table/sticky-headers.components.ts
- stories/table/table.stories.mdx
1. `aui-table`组件默认不设置`overflow`，即`overflow:visible`
直接使用`aui-table`, 无法设置定高，只能由内容撑开高度，实现改动之前的的表格定高溢出内滚动需要配合`auiTableScrollable`指令
2. 新增`story:Header 相对父级元素固定`
3. `auiTableScrollShadow`  更名为 `auiTableScrollable`
在 #372 中 `auiTableScrollShadow` 继承了 `cdkScrollable` , 本次改动该指令也会修改`aui-table`的`overflow`为`auto`, 已经不仅是为滚动表格添加阴影的指令，所以修改命名
`auiTableScrollShadow`依然作为输入属性，禁用表格滚动阴影需要显示设置为`false`
> feat: rm normal table  overflow  mv scroll shadow

- .changeset/cuddly-actors-sing.md
- src/table/table-scroll.scss
`alauda-fe`里对`dialog`里的`table:min-height`设置为了`50px`,不会触发少1px的问题
因为`cell` 文本内容 20px+上下填充共30px 就达到了50px, 不管border设在`cell`上还是`row`都会正常撑开高度
> fix: scroll-table row height less than table 1px

- ng-package.debug.json
https://confluence.alauda.cn/pages/viewpage.action?pageId=133083785
通过 `git update-index –assume-unchanged` 取消对 `ng-package.debug.json` 本地修改的追踪 ，虽然可以不修改远程仓库的状态
但是在远程仓库对 `ng-package.debug.json` 的修改后拉取，或本地 checkout 到其他没有该文件的分支，会导致操作失败需要额外的手动处理
所以远程仓库不再保留 `ng-package.debug.json` , 需要调试则在本地自行创建配置，`.gitignore` 会禁用对其的追踪
> feat: no track ng package debug config any more

- .changeset/three-buses-do.md
- src/theme/theme.pipe.ts
In some IDE like webstorm, it shows "method expression is not a function".
> chore: theme pipes add types

- .changeset/friendly-birds-smell.md
- src/input/input.component.scss
- src/input/number-input/number-input.component.scss
border 的值并不是固定的 1px, 会随着浏览器缩放改变，导致之前通过 margin 调整按钮位置的方法会覆盖外层的 border
伪元素也是，通过 width 作为 border, 会在 100% 缩放下比实际 border 要宽
> fix: number-input border blocked

- .changeset/spotty-fishes-beg.md
- src/date-picker/calendar/range-picker-panel/component.ts
传递首次选择的日期即 startDate 给使用者即 minDate or maxDate in options
目的：根据首次选择的日期来动态限制 minDate or maxDate
相关PR：https://gitlab-ce.alauda.cn/frontend/alauda-fe/-/merge_requests/2874
> chore: zoom chart remove date limit AIT-28225

- .changeset/heavy-beans-do.md
- src/time-picker/panel/panel.component.ts
相关 Issue: https://github.com/stackblitz/core/issues/2541
> feat: mod panel host binding method

- .changeset/stupid-geese-sleep.md
- src/dialog/dialog.component.scss
- src/message/message.component.scss
- src/notification/notification.component.scss
- src/theme/style.scss
- src/tooltip/tooltip.component.scss
单页里依赖 tooltip 等其他组件来加载 cdk 样式，而单独使用 drawer 没有加载 cdk 的样式
> fix: overlay-prebuilt not working

- .changeset/slow-brooms-search.md
- src/tree-select/tree-node.component.html
- src/tree-select/tree-node.component.scss
- stories/tree-select/tree-select.component.ts
原来的层级关系不清晰，容易选错: 比如 c、c-1、c-2 应该对齐，c-0、c-0-1、c-0-2 不应该对齐
变更之后如下：
> fix: fix tree hierarchical relationship

- .changeset/thirty-knives-refuse.md
- src/back-top/back-top.component.html
- src/back-top/back-top.component.scss
- src/back-top/back-top.component.ts
- src/back-top/back-top.module.ts
- stories/back-top/inscroll.stories.ts
> feat: back top style #ASM-14132

- .changeset/clever-lamps-scream.md
- src/autocomplete/autocomplete.component.ts
- src/select/base-select.ts
当过滤发生改变时options也会跟着改变，如果option的文本宽度不一致，也就是下拉选择面板的宽度发生变化时，如果不更新位置，则下拉面板和输入框会显示错位，例如：
> fix: position when option update

- .changeset/eighty-pugs-mix.md
- src/autocomplete/autocomplete.component.ts
如果 autocomplete 的 option 是异步数据会把 placeholder 也展现出来
> fix: autocomplete will show placeholder when sync option

- .changeset/blue-comics-sparkle.md
- src/dialog/dialog.component.ts
- src/drawer/component/drawer.component.ts
[[Drawer] Drawer 组件 block 页面滚动事件且会在 resize 后失效](https://github.com/alauda/ui/issues/513)
> fix: drawer scroll strategy adjust

- .changeset/green-planets-act.md
- src/autocomplete/suggestion/suggestion.component.ts
#526 
tags-input 在使用自动填充时似乎有问题，应该不是本次改动导致的，用 #528 跟踪
> fix: autocomplete circle dependencies

- .changeset/gorgeous-snakes-dance.md
- src/form/form-item/form-item.component.scss
按照设计稿 top-position 的 label 下边距为 4px
> fix: form item label top margin bottom use `s`

- .changeset/neat-pots-doubt.md
- src/drawer/component/drawer.component.ts
- src/drawer/drawer.service.ts
- src/drawer/types.ts
1. 使用服务方式不会应用组件设定的默认值
a. 之前是使用 Object.assign(compnent, option)，现在变成服务是唯一打开抽屉方式，组件只是服务的另一个形式，顺序颠倒了，是先组件后服务。所以应该把默认值写到service里，把组件的assign给服务
2. 使用服务的方式关闭后再打开内容还是之前的，不会变，哪怕数据变了
a. 因为之前使用服务的方式关闭会销毁实例，而组件形式因为有两个overlay，销毁的只是服务的overlay，所以aui-drawer组件本身的overlay并没有被销毁，也就是传入的组件并没有被销毁；
b. 之前两种形式的这种差异没有被清晰的意识到，然后受家忍提出“需要缓存”的影响，就改成关闭不销毁了，包括使用服务的方式。后面在验证的时候也只是验证表单状态是否被保留，而没有验证是否可以正常更新内容导致出现问题
c. 新增 disposeWhenHide 配置，默认值是true，也就是关闭即销毁，但组件里默认是false，与之前的行为保持一致
> fix: known drawer issues

- .changeset/stale-dots-speak.md
- package.json
- src/date-picker/calendar/range-picker-panel/template.html
- src/drawer/component/internal/internal.component.html
- src/drawer/component/internal/internal.component.ts
- src/drawer/drawer.service.ts
- src/tabs/tab-group.component.ts
- src/time-picker/panel/panel.template.html
- yarn.lock
> fix(drawer): no default config when using component mode

- .changeset/beige-bananas-grin.md
- src/form/common-form.ts
- src/input/input.component.scss
- src/paginator/__snapshots__/paginator.component.spec.ts.snap
- src/select/base-select.ts
- src/select/multi-select/multi-select.component.html
- src/select/multi-select/multi-select.component.scss
- src/select/multi-select/multi-select.component.ts
- src/select/select.component.html
- src/select/select.component.scss
- stories/select/basic.component.ts
- stories/select/basic.stories.ts
- stories/select/select.mdx
> feat: select support readonly

- .changeset/fifty-hounds-stare.md
- angular.json
- scripts/build.js
- src/table/index.ts
- src/table/table-cell.directive.ts
- src/table/table-column-resizable.directive.ts
- src/table/table-header-cell.directive.ts
- src/table/table-scroll.directive.ts
- src/table/table-scroll.scss
- src/table/table.component.scss
- src/table/table.component.ts
- src/table/table.module.ts
- src/table/table.spec.ts
- src/utils/index.ts
- src/utils/styles-renderer.ts
- stories/table/basic.component.ts
- stories/table/basic.stories.ts
- stories/table/sticky-columns.component.ts
- stories/table/sticky-columns.stories.ts
> feat: table support resize column width

- src/drawer/component/drawer.component.ts
- src/drawer/component/internal/internal.component.ts
- src/drawer/drawer.service.ts
- stories/drawer/basic-drawer.component.ts
> fix: drawer option update sync

- src/drawer/drawer.service.ts
stopPropagation 会导致触发 hideOnClickOutside 的同时，外界的 click 事件失效
> fix: drawer click outside event should not stopPropagation

- .changeset/small-sheep-train.md
- jest.setup.ts
- src/tabs/tab-header.component.ts
在首次渲染的时候, tablist 的尺寸需要 paginator 时不会显示 paginator , 原因是 tablist 变更时 dom 尺寸还未变化, 导致计算值不正确  
目前的实现只监听 viewport 的尺寸变化
处理是使用 ResizeObservable 监听 tablist 的 dom 尺寸变化, 跟 window.resize 同样触发 realign  
不再关注 tabLabelCount 的变化来更新 paginator 显示
> fix: tab header paginator not show without viewport resize

- .changeset/itchy-planets-brush.md
- src/date-picker/calendar/header/style.scss
- src/date-picker/calendar/header/template.html
- src/date-picker/calendar/panel/picker-panel.style.scss
1. 增加了基本 date-picker-panel header 区 年月 之间的分隔符, 通过一个 div.separator 的 margin: 0 use-var(spacing-s) 填充, 当 年和月 都不存在 suffix 的时候, div 内部会显示一个 /
> 之所以使用 div.separator 去填充间隙而不是通过翻译文本自己设置分隔符, 是因为这样做 分隔符文本 也会被当成按钮的一部分显示 hover 样式以及响应点击事件  
2. 原本的充当按钮作用的 \<a\> 替换为正常的 button[aui-button="text"], 并且 header 区增加 flex-wrap: warp
> 使用 button 后  年/月 区块内部不会单独折行(符合预期),而是整行去折.但是仍会有单个区块过长的溢出问题,  要处理的话就要取消 tooltip-info 的 max-width: 400px , 但是大部分场景应该不需要
TODO:
1. 不同语言地区的 年月 顺序不同，可以参照 antd 使用的 rc-picker 的实现
``` javascript
const monthYearNodes = locale.monthBeforeYear ? [monthNode, yearNode] : [yearNode, monthNode];
```
2. aui-range-picker 也会遇到类似 header 过长的溢出问题，需要之后一起解决
> style: date picker panel row main axis between

- .changeset/polite-guests-dance.md
- src/date-picker/trigger/trigger.component.ts
- stories/input/number-input.component.ts
- stories/input/search-input.component.ts
- stories/select/basic.component.ts
- tsconfig.json
之前的 `"baseUrl" : "."` 会让编辑器自动导入其他模块时首选绝对路径,导致 build 产物在被其他项目依赖时 `Error: Module not found: Error: Can't resolve 'src/i18n' in '/home/mrlang/Workspace/alauda/alauda-fe/node_modules/@alauda/ui/fesm2022'`  
修改后 `src/i18n` 此类路径将不可用, 编辑器会首选相对路径, storybook 导入组件模块时使用 `@alauda/ui`
> chore: mod tsconfig to use relative path import
